### ISSUE TITLE
After the code block is indented, the left border is next to the code

### ISSUE THREAD

**Issue by HiramYang** [mugiwara85/CodeblockCustomizer#128]
After the code block is indented, the left border is next to the code.

I have tried this phenomenon in the sandbox and in the Obsidian I use.

<img width="1920" height="1030" alt="Image" src="https://github.com/user-attachments/assets/edd97126-3217-426b-91fc-646b0c98fe6c" />

Obsidian Version Information：
Sandbox environment information:
SYSTEM INFO:
	Obsidian version: v1.9.10
	Installer version: v1.8.10
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Language: zh
	Insider build toggle: off
	Live preview: on
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Codeblock Customizer v1.3.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by mugiwara85** [comment]
Oh, you are right. I forgot to add padding when line numbers are not enabled. If line numbers are enabled, then it is correct. I'll fix it today and get back to you.

**Comment by mugiwara85** [comment]
@HiramYang You can take the current `styles.css` file and overwrite yours with it. That should fix the problem, however I noticed another problem with indented blocks in reading view, which is caused by Obsidian (this wasn't the case earlier). I am currently fixing that, but that could take a little longer. After that is fixed, I will release a new version.

**Comment by HiramYang** [comment]
OK, thank you for your reply

**Comment by HiramYang** [comment]
The version of the plugin I'm currently downloading is 1.3.1, but this issue still hasn't been resolved. I tried downloading the plugin file from github and installing it in obsidian, but the same problem still occurred

<img width="1920" height="1030" alt="Image" src="https://github.com/user-attachments/assets/ff24bcd6-27aa-4d7b-99c8-1f0756c25364" />

<img width="1920" height="1030" alt="Image" src="https://github.com/user-attachments/assets/f147efed-86e3-4948-bec3-761792290551" />

**Comment by mugiwara85** [comment]
I am confused now. This is how it looks on my end:

<img width="1065" height="1172" alt="Image" src="https://github.com/user-attachments/assets/4f81687c-78d3-4c8f-91c7-3851f7f6976f" />

Last time I asked you test the `styles.css` did that work?

**Comment by mugiwara85** [comment]
Also which theme are you using? Maybe that causes it?

**Comment by HiramYang** [comment]
OK, thank you for your reply

**Comment by mugiwara85** [comment]
@HiramYang Fixed in version 1.4.0
